In [5]:
import pandas as pd
print(pd.__version__)

df_QOL = pd.read_csv('Quality_of_Life.csv')
df_QOL.dropna(inplace=True)
df_QOL

2.2.3

,country,Purchasing Power Value,Purchasing Power Category,Safety Value,Safety Category,Health Care Value,Health Care Category,Climate Value,Climate Category,Cost of Living Value,Cost of Living Category,Property Price to Income Value,Property Price to Income Category,Traffic Commute Time Value,Traffic Commute Time Category,Pollution Value,Pollution Category,Quality of Life Value,Quality of Life Category
2,Albania,42.82,'Low',55.52,'Moderate',48.21,'Moderate',86.43,'Very High',40.85,'Low',14.88,'High',36.74,'Moderate',77.25,'High',': 104.16','Low'
4,Algeria,27.60,'Very Low',47.54,'Moderate',54.43,'Moderate',94.82,'Very High',25.31,'Very Low',21.7,'Very High',45.09,'High',63.87,'High',': 98.83','Very Low'
10,Argentina,40.36,'Low',36.36,'Low',68.00,'High',98.28,'Very High',32.65,'Very Low',20.05,'Very High',44.07,'High',50.81,'Moderate',': 115.06','Low'
11,Armenia,36.91,'Very Low',77.81,'High',58.07,'Moderate',63.42,'High',41.84,'Low',20.95,'Very High',29.31,'Low',62.55,'High',': 116.56','Low'
13,Australia,137.58,'Very High',52.71,'Moderate',73.35,'High',93.80,'Very High',64.50,'Moderate',8.25,'Moderate',37.48,'Moderate',26.80,'Low',': 190.69','Very High'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,United States,153.02,'Very High',50.74,'Moderate',67.86,'High',79.14,'High',65.69,'Moderate',3.54,'Very Low',32.91,'Low',36.61,'Low',': 189.14','Very High'
224,Uruguay,57.92,'Low',48.20,'Moderate',68.57,'High',98.04,'Very High',47.39,'Low',12.28,'High',39.52,'Moderate',43.49,'Moderate',': 141.60','Moderate'
226,Uzbekistan,44.66,'Low',71.97,'High',61.82,'High',69.79,'High',24.40,'Very Low',13.08,'High',34.30,'Low',53.07,'Moderate',': 133.78','Moderate'
230,Vietnam,44.49,'Low',59.00,'Moderate',61.32,'High',71.24,'High',26.85,'Very Low',24.77,'Very High',29.62,'Low',84.19,'Very High',': 97.18','Very Low'
235,Zimbabwe,28.76,'Very Low',39.31,'Low',44.80,'Moderate',96.76,'Very High',35.36,'Very Low',17.35,'Very High',27.79,'Low',78.53,'High',': 94.20','Very Low'

In [7]:
df_WHR = pd.read_csv('World-happiness-report-2024.csv')
df_WHR.dropna(inplace=True)
df_WHR

,Country name,Regional indicator,Ladder score,upperwhisker,lowerwhisker,Log GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.741,7.815,7.667,1.844,1.572,0.695,0.859,0.142,0.546,2.082
1,Denmark,Western Europe,7.583,7.665,7.500,1.908,1.520,0.699,0.823,0.204,0.548,1.881
2,Iceland,Western Europe,7.525,7.618,7.433,1.881,1.617,0.718,0.819,0.258,0.182,2.050
3,Sweden,Western Europe,7.344,7.422,7.267,1.878,1.501,0.724,0.838,0.221,0.524,1.658
4,Israel,Middle East and North Africa,7.341,7.405,7.277,1.803,1.513,0.740,0.641,0.153,0.193,2.298
...,...,...,...,...,...,...,...,...,...,...,...,...
138,Congo (Kinshasa),Sub-Saharan Africa,3.295,3.462,3.128,0.534,0.665,0.262,0.473,0.189,0.072,1.102
139,Sierra Leone,Sub-Saharan Africa,3.245,3.366,3.124,0.654,0.566,0.253,0.469,0.181,0.053,1.068
140,Lesotho,Sub-Saharan Africa,3.186,3.469,2.904,0.771,0.851,0.000,0.523,0.082,0.085,0.875
141,Lebanon,Middle East and North Africa,2.707,2.797,2.616,1.377,0.577,0.556,0.173,0.068,0.029,-0.073
142,Afghanistan,South Asia,1.721,1.775,1.667,0.628,0.000,0.242,0.000,0.091,0.088,0.672